name: Container Vulnerability Scanner

on:
  push:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/tahsib/go-app:${{ github.sha }} .
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/tahsib/go-app:${{ github.sha }}'
          format: 'table,sarif'
          output: 'trivy-results.sarif'
      
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
